version: "3.9"

services:
  app:
    container_name: chickenBot
    image: app
    restart: always
    volumes: 
      - ./:/app
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "${PORT}:${PORT}"
