export const roiQuotes: string[] = [
    "Putain de merde, habituellement le silencieux est fourni à l'achat chaque jour.",
    "Mes n****s savent quelle heure il est.",
    "Ils tirent aucun revenu... où est l'hydroponique ?",
    "Un esprit sain dans un corps sain, on mange bien, et pour ma femme de vrais seins...rappelez vous de ces termes!",
    "Le taux de THC dans le poumon est tellement intense qu'il faut bien manger, alors on mange au Commensal.",
    "Ma destinée est guidée par Allah.",
    "Cocaïno rap musique, ta nouvelle dépendance.",
    "Les cables dans mon cou sont diamantés.",
    "Fais appel aux latino-américains, ils sont les meilleurs dans l'importation du biscuit.",
    "Mais crois-tu que quoi, crois-tu que quoi ? Mais cette merde, c'est une merde merde AMERICAINE!",
    "Mes opposants démissionnent comme Tony Blair.",
    "Leur montre...Leur montre vaut...Moins que 100$ !!!",
    "Qu'est ce qui c'putain d'passe?",
    "Seul le manche que j'respecte t'entends! Seul le manche!",
    "Paix à tous mes israéliens, paix à tous mes palestiniens, faut arrêter cette merde et allumer...le calumet de la paix.",
    "On fume trop d'hydroponique, alors on reste dans le biologique.",
    "On t'calotte nous, calotte sur ta bouche!",
    "Tous les arabes que je connais sont fous.",
    "Mon rap est bien cuit, ma cocaine aussi.",
    "Vrais blancs font vraies choses.",
    "Mais ça baigne Chirac! Ca baigne !!",
    "Lorsque Tony Montana lorsque son partenaire se faisait couper la tête avec avec cette chainsaw, tu t'rappelles de cette partie ?",
    "J'ai une tête de fou... j'étudie...pas... et j'aime pas lire.",
    "Mon médaillon touches à mon pénis",
    "Rien à foutre de ton pot de la Jamaïque avec plein de boules dedans, t'entends?",
    "T'as jamais vendu même pas un gramme!",
    "Les fusils sont braqués sur ta petite amie.",
    "Tous ces artistes rêvent à cela. Tous ces artistes ont jamais touché une Porsche, une Cayenne.",
    "Deux pas en avant, deux pas en arrière, tiens ton fusil allons-y!",
    "Le Roi Heenok, c'est comme de l'hydroponique avec le plus haut taux de crime au monde mélangé ensemble.",
    "Mon français excelle plus qu’un africain diplômé de la Sorbonne",
    "Si j'étais blanc, avec la fame que j'ai, ils me couvriraient d'or comme Once Picsou."
]

export const roiUrl: string[] = [
    "http://www.roi-heenok.com/html/images/gifs/watermark/watermark_aaaaaah.gif",
    "http://www.roi-heenok.com/html/images/gifs/watermark/watermark_heineken__2_.gif",
    "http://www.roi-heenok.com/html/images/gifs/watermark/watermark_89point3.gif",
    "http://www.roi-heenok.com/html/images/gifs/watermark/watermark_9911bpgn.gif",
    "http://www.roi-heenok.com/html/images/gifs/watermark/watermark_chien.gif",
    "http://www.roi-heenok.com/html/images/gifs/watermark/watermark_zp5yhqtg.gif",
    "http://www.roi-heenok.com/html/images/gifs/watermark/watermark_brlaaaaa.gif",
    "http://www.roi-heenok.com/html/images/gifs/watermark/watermark_dindedechoix.gif",
    "http://www.roi-heenok.com/html/images/gifs/watermark/watermark_surpaname.gif",
    "http://www.roi-heenok.com/html/images/gifs/watermark/watermark_femme33.gif",
    "http://www.roi-heenok.com/html/images/gifs/watermark/watermark_pour_personne.gif",

]